version: "1"

services:
  to-do-app:
    build: 
      context: .
      target: development
    ports:
      - "5000:5000"
    env_file:
      - path: .env  
    volumes:
      - ./:/usr/src/app:rw
  to-do-app-tests:
    build: 
      context: .
      target: test
    env_file:
      - path: .env.test  
    volumes:
      - ./:/usr/src/app:rw
