name: Build
on: 
  push:
    branches: 
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"


jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker
      run: docker build --target test --tag todo-app:test .
      
    - name: Run tests in Docker
      run: docker run --mount "type=bind,source=$(pwd),target=/usr/src/app" todo-app:test

  send-slack-notification:
      runs-on: ubuntu-latest
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      steps:
          - name: Send GitHub Action failure notification to Slack channel
            if: ${{ github.env.SLACK_WEBHOOK_URL != '' && failure() }}
            uses: slackapi/slack-github-action@v1.26.0
            with:
              payload: |
                {
                  "text": ":x: GitHub Action failed"
                }
          - name: Send GitHub Action success notification to Slack channel
            if: ${{ github.env.SLACK_WEBHOOK_URL != '' && success() }}
            uses: slackapi/slack-github-action@v1.26.0
            run: echo "This ran"
          - name: Send GitHub Action cancelled notification to Slack channel
            if: ${{ github.env.SLACK_WEBHOOK_URL != '' && cancelled() }}
            uses: slackapi/slack-github-action@v1.26.0
            with:
              payload: |
                {
                  "text": ":warning: GitHub Action cancelled by ${{ github.actor }}"
                }
